---
langcode: en
status: true
dependencies:
  config:
  - canvas.component.sdc.vartheme_bs5_rightup.byline
  - canvas.component.sdc.vartheme_bs5_rightup.card-featured
  - canvas.component.sdc.vartheme_bs5_rightup.heading
  - canvas.component.sdc.vartheme_bs5_rightup.rich-text
  - canvas.component.sdc.vartheme_bs5_rightup.taxonomy
  - core.entity_view_mode.node.search_result
  - field.field.media.image.field_media_image
  - field.field.node.podcast.field_description
  - field.field.node.podcast.field_featured_image
  - field.field.node.podcast.field_tags
  - image.style.canvas_parametrized_width
  - media.type.image
  - node.type.podcast
  - taxonomy.vocabulary.tags
  module:
  - file
  - media
  - node
  - options
  - taxonomy
  - user
id: node.podcast.search_result
content_entity_type_id: node
content_entity_type_bundle: podcast
content_entity_type_view_mode: search_result
component_tree:
  a2373e16-07f7-466d-b4bc-19eb7dcfd014:
    uuid: a2373e16-07f7-466d-b4bc-19eb7dcfd014
    component_id: sdc.vartheme_bs5_rightup.card-featured
    component_version: 760a4a6c1117384e
    inputs:
      media_position: start
      media_image:
        sourceType: entity-field
        expression: "\u2139\uFE0E\u241Centity:node:podcast\u241Dfield_featured_image\u241E\u241Fentity\u241C\u241Centity:media:image\u241Dfield_media_image\u241E\u241F{src\u21A0src_with_alternate_widths,alt\u21A0alt,width\u21A0width,height\u21A0height}"
      ratio: ratio-4x3
      fit: object-fit-cover
      card_border: false
      corner_style: rounded-0
      padded: false
      equal_height: false
      stretched_link: true
      link_url:
        sourceType: host-entity-url
        absolute: false
      content_vertical_alignment: align-items-start
      gutters_between: g-4
      columns_xs_size: "12_12"
      columns_sm_size: "12_12"
      columns_md_size: "04_08"
      columns_lg_size: "04_08"
      columns_xl_size: "04_08"
      columns_xxl_size: "04_08"
  1db7ad2e-8d3f-4bd5-972e-42a72664e77d:
    parent_uuid: a2373e16-07f7-466d-b4bc-19eb7dcfd014
    slot: content
    uuid: 1db7ad2e-8d3f-4bd5-972e-42a72664e77d
    component_id: sdc.vartheme_bs5_rightup.taxonomy
    component_version: 6c96c2405efc9655
    inputs:
      label:
        sourceType: entity-field
        expression: "\u2139\uFE0E\u241Centity:node:podcast\u241Dfield_tags\u241E0\u241Fentity\u241C\u241Centity:taxonomy_term:tags\u241Dname\u241E\u241Fvalue"
  77987d9d-e675-4dbd-9ed3-a9086dd4d6b7:
    parent_uuid: a2373e16-07f7-466d-b4bc-19eb7dcfd014
    slot: content
    uuid: 77987d9d-e675-4dbd-9ed3-a9086dd4d6b7
    component_id: sdc.vartheme_bs5_rightup.heading
    component_version: 0889e2ce906c3164
    inputs:
      heading_text:
        sourceType: entity-field
        expression: "\u2139\uFE0E\u241Centity:node:podcast\u241Dtitle\u241E\u241Fvalue"
      level: 3
  5bedbe3f-7bb4-4ebc-88df-62c406984736:
    parent_uuid: a2373e16-07f7-466d-b4bc-19eb7dcfd014
    slot: content
    uuid: 5bedbe3f-7bb4-4ebc-88df-62c406984736
    component_id: sdc.vartheme_bs5_rightup.rich-text
    component_version: 82cd1f087fd469f4
    inputs:
      text:
        sourceType: entity-field
        expression: "\u2139\uFE0E\u241Centity:node:podcast\u241Dfield_description\u241E\u241Fvalue"
      trim: true
      trim_length: 30
      trim_units: words
      suffix: ' ...'
      strip_html: true
  d29c23f7-9fd5-494e-829b-b3736899a98c:
    parent_uuid: a2373e16-07f7-466d-b4bc-19eb7dcfd014
    slot: content
    uuid: d29c23f7-9fd5-494e-829b-b3736899a98c
    component_id: sdc.vartheme_bs5_rightup.byline
    component_version: cc4869187f83aa8b
    inputs:
      author:
        sourceType: entity-field
        expression: "\u2139\uFE0E\u241Centity:node:podcast\u241Duid\u241E\u241Fentity\u241C\u241Centity:user\u241Dname\u241E\u241Fvalue"
      date:
        sourceType: entity-field
        expression: "\u2139\uFE0E\u241Centity:node:podcast\u241Dcreated\u241E\u241Fvalue"
        adapter: unix_to_date
exposed_slots: []
page_variant: ~
...
