---
langcode: en
status: true
dependencies:
  config:
  - core.entity_view_mode.node.search_result
  - field.field.node.podcast_episode.field_audio
  - field.field.node.podcast_episode.field_content
  - field.field.node.podcast_episode.field_description
  - field.field.node.podcast_episode.field_duration
  - field.field.node.podcast_episode.field_episode_number
  - field.field.node.podcast_episode.field_featured_image
  - field.field.node.podcast_episode.field_tags
  - node.type.podcast_episode
  module:
  - user
id: node.podcast_episode.search_result
targetEntityType: node
bundle: podcast_episode
mode: search_result
content:
  content_moderation_control:
    settings: []
    third_party_settings: []
    weight: -20
    region: content
  links:
    settings: []
    third_party_settings: []
    weight: 100
    region: content
hidden:
  field_audio: true
  field_content: true
  field_description: true
  field_duration: true
  field_episode_number: true
  field_featured_image: true
  field_tags: true
  search_api_excerpt: true
...
