---
langcode: en
status: true
dependencies:
  module:
  - node
id: live_feed
label: Live feed
description: ~
handler: simple
handler_configuration: []
entity_settings:
  target_type: node
  handler: default:node
  handler_settings:
    target_bundles:
      news: news
      podcast: podcast
queue_settings:
  min_size: 0
  max_size: 10
  act_as_queue: true
  reverse: false
...
